(function() {var implementors = {
"cmd":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"cmd/cli/repl/struct.Repl.html\" title=\"struct cmd::cli::repl::Repl\">Repl</a>"]],
"common_procedure":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"common_procedure/local/runner/struct.ProcedureGuard.html\" title=\"struct common_procedure::local::runner::ProcedureGuard\">ProcedureGuard</a>"]],
"common_runtime":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"common_runtime/runtime/struct.Dropper.html\" title=\"struct common_runtime::runtime::Dropper\">Dropper</a>"],["impl&lt;E&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"common_runtime/repeated_task/struct.RepeatedTask.html\" title=\"struct common_runtime::repeated_task::RepeatedTask\">RepeatedTask</a>&lt;E&gt;"]],
"common_telemetry":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"common_telemetry/metric/struct.Timer.html\" title=\"struct common_telemetry::metric::Timer\">Timer</a>"]],
"datanode":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"datanode/heartbeat/struct.HeartbeatTask.html\" title=\"struct datanode::heartbeat::HeartbeatTask\">HeartbeatTask</a>"]],
"servers":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"servers/grpc/flight/stream/struct.FlightRecordBatchStream.html\" title=\"struct servers::grpc::flight::stream::FlightRecordBatchStream\">FlightRecordBatchStream</a>"]],
"sqlness_runner":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"sqlness_runner/env/struct.GreptimeDB.html\" title=\"struct sqlness_runner::env::GreptimeDB\">GreptimeDB</a>"]],
"storage":[["impl&lt;'a, S: LogStore&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"storage/engine/struct.SlotGuard.html\" title=\"struct storage::engine::SlotGuard\">SlotGuard</a>&lt;'a, S&gt;"],["impl&lt;S: LogStore&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"storage/compaction/task/struct.CompactionTaskImpl.html\" title=\"struct storage::compaction::task::CompactionTaskImpl\">CompactionTaskImpl</a>&lt;S&gt;"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"storage/sst/struct.FileHandleInner.html\" title=\"struct storage::sst::FileHandleInner\">FileHandleInner</a>"],["impl&lt;R&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"storage/scheduler/struct.LocalScheduler.html\" title=\"struct storage::scheduler::LocalScheduler\">LocalScheduler</a>&lt;R&gt;<span class=\"where fmt-newline\">where\n    R: <a class=\"trait\" href=\"storage/scheduler/trait.Request.html\" title=\"trait storage::scheduler::Request\">Request</a>,</span>"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()